### ISSUE TITLE
User-can-search-for-similar-artists

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for similar artists by providing a genre and artist name.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to select a genre of music and enter an artists name within the search bar.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/148260436-8ab5be29-38f1-4f3c-ac60-bb267b2b2758.png)
![image](https://user-images.githubusercontent.com/93749120/148260560-5759c7d9-5786-40a5-a074-a36abffe0194.png)
![image](https://user-images.githubusercontent.com/93749120/148260622-386d27f2-fd27-4e0e-a4b3-5f00a2cbb68c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create and style HTML elements to match mobile & desktop homepage wireframes.
  - [x] Add a div[data-view="genres"] to the HTML.
- [x] Create and style HTML elements to match mobile & desktop search wireframes.
  - [x] Add a div[data-view="artist-search"] to the HTML.
  - [x] Add an input type="text" box for user to search.
  - [x] Add a submit button attached to search box .
  - [x] Allow user to input artist name in search bar
  - [x] Add a div with text content below search box and center it.
- [x] Swap from [data-view="genres"] to div[data-view="search"] when user clicks on a genre.
- [x] Create an XMLHttpRequest object to get the data(artists and video) when the user submits search.

- **Clean Up**
- - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
