### ISSUE TITLE
User-can-view-list-of-artists

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of similar artists.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user types in the artist name in the input text box and clicks search, a list of similar artists and a corresponding YouTube video will appear below the search bar. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/148475308-dcd324bd-ee80-43f5-a583-89649b16ffd8.png)
![image](https://user-images.githubusercontent.com/93749120/148705926-b1331a56-ae24-43d6-b3fb-ad170819f4cb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user submits artist name, search button background color gets darker on click.
- [x] When user clicks submit, vibes message text content changes to "Similar Vibes".
- [x] Add an empty unordered list to the div[data-view="artist-search"] element in the HTML. (below vibes message)
- [x] Add some dummy artist results to the unordered list in the HTML and style them to match the wireframes

- [x] Create a function that generates the DOM tree for each artist in the data.artists array and append the new DOM elements to the div with the class="results-row"
- [x]  Create a function for appending the newly created DOM elements to the page.
  - [x] loop through the similar artist objects that are stored inside of the data.artists array.
  - [x] make sure each object that is returned has a YouTube URL. Do NOT include if 'yUrl: null' - (guard)
  - [x] check if the new array contains 6 objects, if so, stop the loop.
- [x] Remove the example HTML results once the user's search results are successfully being appended to the DOM on page load.
- [x] Make nav bar logo swap views to genres home page

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
