### ISSUE TITLE
User-can-add-artists

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/149223333-4f081092-a2a7-4173-8569-93dc154580a2.png)
![image](https://user-images.githubusercontent.com/93749120/149223510-ce04c349-6994-4822-aa0d-9f122058bae3.png)
![image](https://user-images.githubusercontent.com/93749120/149223533-ec83d051-3a9f-4f70-ab98-4f20e09d93be.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a '+' icon next to each similar artists name.
- [x] Change the '+' icon to a darker orange when hovered.
- [x]  Change the '+' icon's color to white when user clicks on it.
- [x] Revise view swapping function to utilize any view
  - [x] call swapView function when pressing app logo and genre box
- [x] Ensure that each artist within data.artists has its own artist ID
- [x] Create a function that
  - [x] remove the DOM of the selected artist from the current view on click
  - [x] store the liked artist into data.likedArtists
