### ISSUE TITLE
User-can-view-liked-artists

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an artist from the list of search results, and view the artist in a 'Liked Artists' page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the search results show up on the page, user will be able to click on the '+' icon. Once the icon is clicked, that artist is removed from the current view and added to the Artists tab on the nav. The Artists tab will take user to the Liked Artists page where the user will be able to view all their liked videos.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/149672809-67887758-c84f-42cf-9eee-db5973c27a76.png)

![image](https://user-images.githubusercontent.com/93749120/149672777-50c9dabb-774c-47de-929a-7b9343b04ee8.png)
![image](https://user-images.githubusercontent.com/93749120/149672795-420f9c04-a06f-4dff-9042-48935278a63d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an artists link on nav bar
  - [x] change color to darker blue when hovered over
  - [x] add 'liked-artists' data-view to the artists link
- [x] Create a new data-view 'liked-artists' that has a 'Liked Artists' header
  - [x] generate DOM of liked artists onto the page from the data.likedArtists array
- [x] Create a function for saving liked artist data to local storage

**Comment by MohamadAlsyouf** [comment]
<div class="row align-items-center space-between">
            <h2 data-view="home-page" class="app-name"><img data-view="home-page" id="logo-img" src="images/viberr-logo.png" alt="viberr-logo">Viberr</h2>
            <a data-view="liked-artists" class="artist-nav" href="#">Artists</a>
          </div>
.artist-nav {
  text-decoration: none;
  font-size: x-large;
  color: #1e5192;
}
