### ISSUE TITLE
User-can-delete-an-artist

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove an artist from their Liked Artists page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user views their liked artists, they will be able to remove a specific artist by clicking on a minus icon. Once the minus icon is clicked, the artist and corresponding video will be removed from their Liked Artists page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/156857338-22f3260b-f51d-4663-8954-4406874ec2df.png)
![image](https://user-images.githubusercontent.com/93749120/156857371-a6587207-cd58-4a2c-aac9-3ad010ac2516.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a span beneath the Liked Artists header indicating whether or not there are any liked artists.
- [x] Insert a clickable minus icon on each DOM child rendered
- [x] Update likeArtist function to removes an artist from the DOM on minus click
  - [x] also remove the selected artist from the data.likedArtists array
- [x] Implement data.view property to keep track of and maintain the current view in local storage
